version: '3.8'

services:
  angular-dev:
    container_name: my-angular-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./angular-app:/app
      - /app/node_modules
    working_dir: /app
    # Add this to ensure the node user can write to the mounted volumes
    user: node
    restart: unless-stopped