FROM node:latest as builder

WORKDIR /angular-app

COPY angular-app/package*.json

RUN npm install # This will now run in /angular-app and find the copied package.json

COPY angular-app/. ./

RUN npm test -- --no-watch --reporters=default --code-coverage # Runs in /angular-app

RUN ng build --configuration production # Runs in /angular-app

FROM nginx:alpine as runner

COPY --from=builder /angular-app/dist/my-angular-app /usr/share/nginx/html
