FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY /angular-app/package*.json ./

# Install dependencies
RUN npm install
RUN npm install -g @angular/cli

# The source code will be mounted as a volume in docker-compose.dev.yml
# so we don't need to copy it here

# Expose port for Angular development server
EXPOSE 4200

# Start Angular development server with host 0.0.0.0 to make it accessible outside the container
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll=2000"]