name: Build & Push Docker Image

on:
  push:
    branches:
      - main # Or master, or whichever branch triggers the pipeline

jobs:
  build:
    runs-on: ubuntu-latest # The environment where the job will run

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Action to get your source code
        with:
          submodules: 'recursive'

      - name: Set up Docker Buildx
        # Required for building and pushing to registries
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub two
        # Replace docker.io with your registry if not using Docker Hub
        uses: docker/login-action@v3
        with:
          # You need to set these as secrets in your GitHub repository settings
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} # Or DOCKER_HUB_PASSWORD

      - name: Extract Docker metadata
        # This action helps generate proper tags automatically (e.g., based on branch, commit SHA)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            hseleirodocker/angular-app
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Look for Dockerfile in the current directory
          file: ./Dockerfile.dev
          push: true # Push the image to the registry after building
          tags: ${{ steps.meta.outputs.tags }} # Use the generated tags
          labels: ${{ steps.meta.outputs.labels }} # Add labels from metadata
          cache-from: type=gha # Enable caching layers for faster builds
          cache-to: type=gha,mode=max # Enable caching layers for faster builds
